version: '3'

services:
  ws:
    restart: always
    build: './src/ws'
    volumes:
      - './src/ws:/app'
      - './data:/data'
    ports:
      - '8000:80'
  ee:
    restart: always
    build: './src/ee'
    volumes:
      - './src/ee:/app'
      - './data:/data'
